### ISSUE TITLE
Add serverless:list functions command.

### ISSUE THREAD

**Issue by Xabadu** [twilio-labs/vscode-twilio#13]
Add support for the `serverless:list` CLI command.

This should include:

- Command Palette prompt with the message: `Twilio Serverless: List Functions`
- A function that executes the command in the terminal and displays the list of existing functions as output.
- Update the README with a description of this feature.

**Comment by gagandeepp** [comment]
@Xabadu  Can you please assign this to me?

**Comment by Xabadu** [comment]
@gagandeepp you got it! Thanks for taking on this. 

If you have any questions, please don't hesitate to reach out ✌️

**Comment by gagandeepp** [comment]
Can you please share me list of existing functions as mentioned in point 2?

**Comment by Xabadu** [comment]
@gagandeepp is the list of the functions that you currently have in your account. If you install the cli and run `twilio serverless:list functions` in your terminal, that's the output we want to achieve with this.

You can find more information about the cli list command [here](https://github.com/twilio-labs/plugin-serverless#twilio-serverlesslist-types) - that currently has options for different types of things you can list, but for this change, doing functions is good for now :)
