### ISSUE TITLE
Expand serverless:list command to other types

### ISSUE THREAD

**Issue by Xabadu** [twilio-labs/vscode-twilio#25]
We currently support listing the existing functions for an account (See #15 and #18 for details), and we need to add support for the rest of the `types` that can be listed (services, environments, assets, variables) as well as a default option that will list everything is no params are passed.

A full list of options is available [here](https://github.com/twilio-labs/plugin-serverless#twilio-serverlesslist-types)

This needs to include a Command Palette option for every type that we'll be able to list through this and updates to the README with the new features included.

**Comment by babhishek21** [comment]
Hi there! Can I work on this?

**Comment by Xabadu** [comment]
@babhishek21 you got it! Thank you.

Let us know if you have any questions about this.

**Comment by babhishek21** [comment]
@Xabadu Do you want to track each of the types separately, or shall we just keep add milestones to this issue?

- [ ] services
- [ ] environments
- [x] functions
- [ ] assets
- [ ] variables

**Comment by babhishek21** [comment]
Hi @Xabadu I tried setting up the project and debugging the extension through __vs-code__ and ran into ES6/Node incompatibility issues.

Whenever I try to Debug (`F5`) the extension, and try running any of the commands from the palette, the engine fails with a syntax error:
```
Activating extension `Twilio.vscode-twilio` failed:  Unexpected token {
extensionHostProcess.js:496
Here is the error stack:  /Users/redacted/misc/vscode-twilio/extension.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { import { installDependencies } from './helpers/onInitDependencyInstaller';
                                                                                                                                                                  ^

SyntaxError: Unexpected token {
```
The error makes sense: `import`s are not fully supported in Node, so we probably need an ES5 to ES5 transpiler. But I couldn't see any `babel` configurations (neither `package.json` nor `.babelrc`) , nor any vs-code extension configuration (`launch.json`). 

The `jsconfig.json` file mentions **commonjs/es6**, but the __vs-code__ debugger doesn't seem to be picking that up. Am I missing something here?

**Comment by Xabadu** [comment]
@babhishek21 adding milestones here should be fine. I think this PR should take care of all the remaining types :)

Not sure about the error. I think vscode should take care of that internally, but I'll take a look asap and keep you posted.

**Comment by Xabadu** [comment]
@babhishek21 do you mind pulling from `master` and trying again? I fixed the bugs that were causing issues there, so it should work now.
